"""Read-only data port of the analytics layer. Implemented structurally by
app.storage.analytics_read.SQLiteAnalyticsReader (analytics never imports storage)."""
from __future__ import annotations

from datetime import datetime
from typing import Protocol

from app.domain.market import Candle
from app.domain.research_lab import OutcomeObservation, SimulatedTrade


class AnalyticsSource(Protocol):
    def table_names(self) -> set[str]: ...
    def table_count(self, table: str) -> int: ...
    def triggers_of(self, table: str) -> list[str]: ...
    def migrations(self) -> list[str]: ...
    def list_runs(self, kind: str | None = None) -> list[dict]: ...
    def run(self, run_id: str) -> dict | None: ...
    def dataset(self, dataset_id: str) -> dict | None: ...
    def trades(self, run_id: str) -> list[SimulatedTrade]: ...
    def trade_rows(self, run_id: str | None = None) -> list[dict]: ...
    def equity(self, run_id: str) -> list[tuple[datetime, float]]: ...
    def observations(self, run_id: str) -> list[dict]: ...
    def outcomes(self, run_id: str) -> list[OutcomeObservation]: ...
    def outcome_rows(self) -> list[dict]: ...
    def run_ids_of(self, table: str) -> set[str]: ...
    def live_setups(self, symbol: str | None = None, timeframe: str | None = None) -> list[dict]: ...
    def setup_events(self) -> list[dict]: ...
    def regime_snapshots(self, symbol: str | None = None, timeframe: str | None = None) -> list[dict]: ...
    def structure_events(self) -> list[dict]: ...
    def snapshot_quality(self, table: str) -> dict[str, int]: ...
    def monitor_runs(self) -> list[dict]: ...
    def monitor_events(self, run_id: str | None = None) -> list[dict]: ...
    def conflicts(self) -> dict[str, list[dict]]: ...
    def candles(self, symbol: str, timeframe: str, start: datetime, end: datetime) -> list[Candle]: ...
