from __future__ import annotations

from datetime import datetime
from typing import Protocol


class MonitorRunStore(Protocol):
    """Persistence of runtime state (implemented in app/storage/monitor.py)."""

    def start_run(self, run_id: str, started_at: datetime, config: dict, meta: dict) -> None: ...
    def heartbeat(self, run_id: str, at: datetime, status: str, health: dict) -> None: ...
    def record_event(self, run_id: str, event: dict) -> None: ...
    def stop_requested(self, run_id: str) -> bool: ...
    def finish_run(self, run_id: str, at: datetime, status: str, health: dict, summary: dict) -> None: ...
