#!/usr/bin/env python3
"""Generate docs/V070_FEATURE_CATALOG.md from the registry (single source of truth)."""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from app.research.features.catalog import DEFAULT_REGISTRY  # noqa: E402

UNITS = {"quote": "quote currency (USDT)", "base": "base coin", "fraction": "dimensionless fraction (0.01 = 1 %)",
         "log": "natural-log return units", "ratio": "dimensionless ratio", "count": "number of bars",
         "per_1m_quote": "|log return| per 1,000,000 quote turnover"}
INTERP = {
    "returns": "Bar-level price change / range. Descriptive, no smoothing.",
    "trend": "Level and direction of smoothed price. Distances/slopes are relative (fractions).",
    "volatility": "Dispersion of price changes. ATR = range-based (price units); std/realized = return-based.",
    "volume": "Traded quantity (base) and notional (quote). Never mixed; never called CVD.",
    "structure": "Position of price relative to the recent range; liquidity proxies. Not SMC/BOS.",
}

out = ["# QRE v0.7.0 — Feature Catalog (generated)", "",
       "Generated by `scripts/gen_feature_catalog.py` from the registry; do not edit by hand. "
       "Formula hashes are pinned in `app/research/features/VERSIONS.lock`.", "",
       "Common policy for every feature below: **closed candles only** (bars with close_time <= as_of), "
       "**gap-strict** (max_gap_bars = 0: the most recent contiguous run must contain `min_observations` bars; "
       "gaps are never filled), status instead of fallback values. Timeframe: any of 1m/5m/15m/1h/4h/1d; "
       "`lookback`/`warmup` are in bars of that timeframe.", ""]
for fam in ("returns", "trend", "volatility", "volume", "structure"):
    out += [f"## {fam.capitalize()}", "", INTERP[fam], ""]
    for s in DEFAULT_REGISTRY.latest():
        if s.family != fam:
            continue
        tag = " — PROXY" if s.is_proxy else (" — NOT IMPLEMENTED" if not s.implemented else "")
        out += [f"### `{s.key}`{tag}", "",
                f"- **Formula:** {s.description}",
                f"- **Unit:** {UNITS.get(s.unit, s.unit)}",
                f"- **Lookback:** {s.lookback} · **Warmup:** {s.warmup} · **Min observations:** {s.min_observations}",
                f"- **Params:** `{dict(s.params)}` · **Formula hash:** `{s.formula_hash}`"]
        if s.is_proxy:
            out.append(f"- **Proxy for:** `{s.proxy_for}` — {s.limitations}")
        if not s.implemented:
            out.append(f"- **Status:** always NOT_AVAILABLE — {s.not_implemented_reason}")
        out.append("")
(ROOT / "docs" / "V070_FEATURE_CATALOG.md").write_text("\n".join(out))
print(f"wrote catalog with {len(DEFAULT_REGISTRY.latest())} features")
